### ISSUE TITLE
It can be even more strict

### ISSUE THREAD

**Issue by cometkim** [kripod/gatsby-starter-strict#874]
Hi @kripod, It looks a nice starter!

You can make this starter even more strict, for Gatsby queries,

https://github.com/cometkim/gatsby-plugin-typegen

Do you like to try to use the typegen plugin to make all queries type-safe and lint it with https://github.com/apollographql/eslint-plugin-graphql?

**Comment by kripod** [comment]
Hi @cometkim!

Thank you! I was thinking about it, but decided not to over-complicate the project’s configuration. Please feel free to create a fork of the project and publish it under a different name or scope.
